[package]
name = "polars_text"
version = "0.1.0"
edition = "2021"

[lib]
name = "polars_text"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
candle-core = "0.9.2"
candle-nn = "0.9.2"
candle-transformers = "0.9.2"
hf-hub = "0.4.3"
linfa = "0.7"
linfa-clustering = "0.7"
ndarray = "0.15"
once_cell = "1.19"
polars = { version = "0.52.0", default-features = false, features = ["fmt", "dtype-struct"] }
pyo3 = "0.26"
pyo3-polars = { version = "0.25.0", features = ["derive"] }
regex = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokenizers = "0.22.2"
